export const CLICK_UPDATE_VALUE = 'CLICK_UPDATE_VALUE';
export const CLICK_DELETE_VALUE = 'CLICK_DELETE_VALUE';
export const CLICK_EDIT_VALUE = 'CLICK_EDIT_VALUE';
export const CLICK_ADD = 'CLICK_ADD';
export const CLICK_UPDATE_NOTA = 'CLICK_UPDATE_NOTA';